### ISSUE TITLE
target url directly 

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#189] opened 2020-04-20 06:22 UTC
I am curious whether is worth set up the following feature or already have it? 

target url directly access to garden/shoot/seed/project

eg
`https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-i333878/shoots/ez6hydlg6k/`

as we can see from url we already have shoots name `ez6hydlg6k`, namespace `garden-i333878`,  project`i333878` , canary with Suffix `-virtual`. I haven't figure out seed yet, will check it later 

as expect it will be act just copy url from the dashboard page only then 
`gardenctl target  shoot https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-i333878/shoots/ez6hydlg6k/` to access shoot 

`gardenctl target  seed https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-i333878/shoots/ez6hydlg6k/` to access seed 

 
Accept criteria:
gardenctl target project|garden|seed|shoot|namespace url 

Let me know any concerns and assign it to me if worth it

**Comment by DockToFuture** [comment] 2020-04-20 06:27
There is a similiar issue open #188 by targeting the cluster via url. We can also add this to the target function as you specified. Maybe you want to sync here with @neo-liang-sap.

**Comment by tedteng** [comment] 2020-04-20 06:40
thanks

**Comment by petersutter** [comment] 2020-04-20 07:15
See also https://github.com/gardener/dashboard/pull/657

**Comment by tedteng** [comment] 2020-04-20 08:22
@petersutter  that looks awesome which also similar what I want to do as well. copy and paste without typing too much 

should I still keep this ticket open working on that or just close it because you already provide the feature. ?

**Comment by petersutter** [comment] 2020-04-20 09:44
I had deleted my response to which you are referring because I thought that this was a duplicate of the target server command. My response pointed to the corresponding dashboard pr https://github.com/gardener/dashboard/pull/657

But it still makes sense to close this PR and continue the discussion in https://github.com/gardener/gardenctl/issues/188

**Comment by tedteng** [comment] 2020-04-20 09:46
sure agree and close ticket

**Closed** 2020-04-20 09:56 UTC
